function D = Dfun(omega,k)
%DFUN
%    D = DFUN(OMEGA,K)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    03-May-2016 10:37:01

t2 = 1.0./k.^2;
t3 = sqrt(2.0);
t4 = 1.0./k;
t5 = sqrt(pi);
t7 = omega.*t4.*2.0;
t6 = t7-9.0;
D = t2.*(t3.*t5.*t6.*exp(t6.^2.*(-1.0./2.0)).*(erfi(t3.*t6.*(1.0./2.0))-1i).*(1.0./2.0)-1.0).*(-2.0./5.0)-t2.*(omega.*t3.*t4.*t5.*exp(omega.^2.*t2.*(-1.0./2.0)).*(erfi(omega.*t3.*t4.*(1.0./2.0))-1i).*(1.0./2.0)-1.0).*(9.0./1.0e1)+1.0;
